lsi: true
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-architect
title: ELTOROIT - Electronics
description: Diary of a developer learning about the fascinating world of electronics (mechatronics, robotics, IoT). Join me, and learn together.
show_downloads: false
