lsi: true
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-architect
title: ELTOROIT's Journey
description: Diary of a Salesforce developer on the magical world of electronics and IoT. Join me, as I share my experiences in this fantastic world. Let's learn together!
show_downloads: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
url: "https://eltoroit.github.io/"
