lsi: true
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-architect
show_downloads: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
# Search Engine
title: JS4IoT.com
url: "https://www.js4iot.com/"
tagline: Diary of a JavaScript developer on the magical world of IoT and electronics
description: Diary of a JavaScript developer working on electronics and IoT primarily using Raspberry Pi. Join me, as I share my experiences in this fantastic world. Let's learn together! Tutorials, demos, explanations. Understand how Raspberry Pi, Node.js, IoT, and other technologies can interact together.
author:
  twitter: eltoroit
social:
  name: Andres Perez (ELTOROIT) @ JS4IoT.com
  links:
    - https://www.linkedin.com/in/eltoroit
    - https://twitter.com/eltoroit
    - https://github.com/eltoroit
    - https://trailblazer.me/id/eltoroit
