# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll"

git_source(:github) {|repo_name| "https://github.com/eltoroit/eltoroit.github.io" }

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
    gem 'jekyll-sitemap'
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag'
end