# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/eltoroit/eltoroit.github.io" }

# gem "rails"

gem "jekyll"

gem "github-pages", group: :jekyll_plugins